name: QA Backend

on: [push, workflow_dispatch]

jobs:
  ejecutar-back:
    uses: digital-gob-cl/QA-workflows/.github/workflows/motor-generic.yml@main
    with:
      repo_to_test: 'digital-gob-cl/dd-automatizacion-qa'
      npm_command: 'test:api'
      tags: '@API'
    secrets:
      REPO_ACCESS_TOKEN: ${{ secrets.GH_PAT }}
      CLAVE_UNICA_PASS: ${{ secrets.CLAVE_UNICA_PASS }}